### ISSUE TITLE
Add command line executable

### ISSUE THREAD

**Issue by AlaaSarhan** [CodingWhales/cw_translate#4]
Implement executable for command line usage.
- [x] setup basic interface

**Comment by AlaaSarhan** [comment]
@irmela I just added the Config class in #3 PR just for the general architecture to be complete .. but will leave implementation of config loading to this PR

**Comment by irmela** [comment]
@AlaaSarhan I'd prefer to continue working on this later since some things will change (for example with #5) that's why I only added a basic implementation. Will add a new issue for the enhancement.
